import React from "react";
import Head from "next/head";
import NextLink from "next/link";
import {
  AppBar,
  Container,
  Link,
  Toolbar,
  Typography,
} from "@material-ui/core";
import useStyles from "../utils/styles";

function Layout({ title, description, children }) {
  const classes = useStyles();
  return (
    <div>
      <Head>
        <title>{title ? `${title}-Next AmazonB` : "Next AmazonB"}</title>
        {description ? (
          <meta name="description" content={description} />
        ) : (
          <meta name="description" content="Generated by create next app" />
        )}
      </Head>
      <AppBar position={"static"} className={classes.navbar}>
        <Toolbar>
          <NextLink href={"/"} passHref={true}>
            <Link>
              <Typography className={classes.brand}>AmazonB</Typography>
            </Link>
          </NextLink>
          <div className={classes.grow} />
          <NextLink href={"/cart"} passHref={true}>
            <Link>
              <Typography>cart</Typography>
            </Link>
          </NextLink>
          <NextLink href={"/login"} passHref={true}>
            <Link>
              <Typography>Login</Typography>
            </Link>
          </NextLink>
        </Toolbar>
      </AppBar>
      <Container className={classes.main}>{children}</Container>
      <footer className={classes.footer}>
        All rights reserved by next amazonb.
      </footer>
    </div>
  );
}

export default Layout;
